import { NextResponse } from "next/server";
import { getSession } from "@backend/lib/auth";
import { prisma } from "@backend/lib/prisma";

export const dynamic = "force-dynamic";

export async function GET(req: Request) {
  const session = await getSession();
  if (!session?.user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

  const url = new URL(req.url);
  const caseId = url.searchParams.get("caseId");
  if (!caseId) return NextResponse.json({ error: "caseId required" }, { status: 400 });

  const c = await prisma.investigationCase.findUnique({
    where: { id: caseId },
    include: {
      entities: true,
      relationships: { include: { source: true, target: true } },
      events: { orderBy: { eventAt: "asc" } },
      documents: { include: { blockchainRecords: { orderBy: { index: "asc" } } } },
    },
  });
  if (!c) return NextResponse.json({ error: "Case not found" }, { status: 404 });

  // Patterns relevant to the case.
  const relatedNames = new Set(c.entities.map((e) => e.name));
  const patterns = (await prisma.pattern.findMany()).filter((p) => {
    const names = JSON.parse(p.entities ?? "[]") as string[];
    return names.some((n) => relatedNames.has(n));
  });

  const firstDoc = c.documents[0];
  const block = firstDoc?.blockchainRecords?.[0];

  await prisma.auditLog.create({
    data: {
      userId: (session.user as { id?: string }).id,
      action: "REPORT_GENERATED",
      detail: `Generated report for ${c.caseId}`,
      status: "SUCCESS",
    },
  });

  const report = {
    caseId: c.caseId,
    title: c.title,
    status: c.status,
    generatedAt: new Date().toISOString(),
    entities: c.entities.map((e) => ({ name: e.name, type: e.type })),
    relationships: c.relationships.map((r) => ({
      a: r.source.name,
      b: r.target.name,
      type: r.type,
      strength: r.strength,
    })),
    events: c.events.map((e) => ({ summary: e.summary, eventAt: e.eventAt.toISOString() })),
    patterns: patterns.map((p) => ({ title: p.title, severity: p.severity, summary: p.summary })),
    crypto: {
      storedHash: firstDoc?.sha256 ?? "n/a",
      blockIndex: block?.index ?? null,
      verified: firstDoc?.verified ?? false,
    },
    audit: [
      `Case created: ${c.caseId}`,
      "Evidence notarized on prototype blockchain ledger",
      `Report generated by ${session.user.name ?? "investigator"}`,
      "AI outputs marked as investigative leads requiring verification",
    ],
  };

  return NextResponse.json({ report });
}
